= Install Red Hat Cluster Advanced Management Operator

Red Hat Advanced Cluster Management (RHACM) is installed through Operator Lifecycle Manager (OLM), which manages the installation, upgrade, and removal of the components.

NOTE: OpenShift Container Platform required access: Cluster administrator (cluster-admin) permissions.

The OpenShift Container Platform provided in this lab meet the minimal https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.6/html/install/installing#requirements-and-recommendations[requirements] from the official documentation. The cluster hub components will be installed on worker nodes, no https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.6/html/install/installing#installing-on-infra-node[infrastructure] nodes will be provided.

== Installing from the OperatorHub web console interface

[#install]
== Installing from the OpenShift Container Platform CLI

You can proceed to install Red Hat Advanced Cluster Management from the CLI, run the following commands

* Before install run the installation, take a few seconds to review this YAML file `install/01_acm-operator.yaml` which defines the following resources:
** `open-cluster-management` namespace
** `open-cluster-management-rhte2023` OperatorGroup
** `advanced-cluster-management` subscription

[.lines_space]
[.console-input]
[source,yaml, subs="+macros,+attributes"]
----
--- file install/01_acm-operator.yaml
--- Create Namespace 
apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management
--- Create Operator Group
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: open-cluster-management-rhte2023
  namespace: open-cluster-management
spec:
  targetNamespaces:
  - open-cluster-management
--- Create Subscription / Install Operator
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: advanced-cluster-management
  namespace: open-cluster-management
spec:
  channel: release-2.6
  installPlanApproval: Automatic
  name: advanced-cluster-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: advanced-cluster-management.v2.6.3
----


* Install Red Hat Advanced Cluster Management Operator and verify that the installation is completed successfully as follows:

[.lines_space]
[.console-input]
[source,bash, subs="+macros,+attributes"]
----
oc apply -f install/01_acm-operator.yaml
----

[.lines_space]
[.console-input]
[source,shell, subs="+macros,+attributes"]
----
oc get csv advanced-cluster-management.v2.6.3

NAME                                 DISPLAY                                      VERSION   REPLACES                             PHASE
advanced-cluster-management.v2.6.3   Advanced Cluster Management for Kubernetes   2.6.3     advanced-cluster-management.v2.6.2   Succeeded
----

[#setup]
= Setup a MulticlusterHub

Once the RHACM Operator is already completed, proceed with the next step to create RHACM cluster hub, and verify the installation checking that the hub cluster status is in `Running` and all pods in namespace `open-cluster-management` are also in `Running` status:

* Before create RHACM cluster, take a few seconds to review this YAML file `install/02_acm-multicluster.yaml` which defines the following resources:
** `MultiClusterHub` object

[.lines_space]
[.console-input]
[source,yaml, subs="+macros,+attributes"]
----
--- Create MultiClusterHub Custom Resource
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
spec: {}
----

and run the following commands to create MultiClusterHub as follows:

[.lines_space]
[.console-input]
[source,bash, subs="+macros,+attributes"]
----
oc apply -f install/02_acm-multicluster.yaml

oc get mch -o=jsonpath='{.items[0].status.phase}' -n open-cluster-management

oc get pod -n open-cluster-management
----

If the cluster hub is in `installing` status indefinitely, check the operator logs as follows:

[.lines_space]
[.console-input]
[source,bash, subs="+macros,+attributes"]
----
oc logs multiclusterhub-operator-xxx-xxx -n open-cluster-management
----

[#console]
= Access to the MultiCluster WebConsole

Once the RHACM cluster hub installation is completed, proceed getting the route where you will find your ACM Console's:

[.lines_space]
[.console-input]
[source,shell, subs="+macros,+attributes"]
----
oc get routes

NAME                 HOST/PORT                                          PATH   SERVICES             PORT    TERMINATION          WILDCARD
multicloud-console   multicloud-console.apps.jclaretm.nasatam.support          management-ingress   https   reencrypt/Redirect   None
----

[#gitops]
= Integrate GitOps Operator

RHACM introduces a new `gitopscluster` resource kind, which connects to a `placement` resource to determine which clusters to import into Argo CD. This integration allows you to expand your fleet, while having Argo CD automatically engage in working with your new clusters. This means if you leverage Argo CD `ApplicationSets``, your application payloads are automatically applied to your new clusters as they are registered by RHACM in your Argo CD instances.

In order to integrate the Red Hat GitOps operator and the Advance Cluster Management cluster hub already deployed, run the following commands:

* Before proceed with the steps to integrate the GitOps Operator with RHACM, take a few seconds to review this YAML file `03_acm-gitops.yaml` which defines the following resources:
** `openshift-gitops` namespace
** `openshift-gitops-opertator` subscription
** `gitops-clusters` ManagedClusterSet
** `gitops-clusters` ManagedClusterSetBinding
** `gitops-clusters` Placement
** `argo-acm-importer` GitOpsCluster and
** `cluster` GitopsService

[.lines_space]
[.console-input]
[source,bash, subs="+macros,+attributes"]
----
--- file install/03_acm-gitops.yaml
--- Create Namespace for GitOps operator
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops
---
--- Create Subscription / Install Operator
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-operators
spec:
  channel: gitops-1.6
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: openshift-gitops-operator.v1.6.1
---
--- Create Managed cluster set for Gitops Cluster
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ManagedClusterSet
metadata:
  name: gitops-clusters
spec: {}
---
--- Create ManagedClusterSet Binding
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ManagedClusterSetBinding
metadata:
  name: gitops-clusters
  namespace: openshift-gitops
spec:
  clusterSet: gitops-clusters
---
--- Create Placement for clusters with key vendor in Openshift
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: gitops-clusters
  namespace: openshift-gitops
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: vendor
          operator: "In"
          values:
          - OpenShift
---
--- Create Gitops instance cluster
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: argo-acm-importer
  namespace: openshift-gitops
spec:
  argoServer:
    cluster: local-cluster
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1alpha1
    name: gitops-clusters
    namespace: openshift-gitops
---
--- Create Gitops service
apiVersion: pipelines.openshift.io/v1alpha1
kind: GitopsService
metadata:
  name: cluster
spec: {}
----

Run the following commands to perform the GitOps Operator integration with RHACM

[.lines_space]
[.console-input]
[source,bash, subs="+macros,+attributes"]
----
oc apply -f install/03_acm-gitops.yaml

oc apply -f install/04_acm-gitopservice.yaml
----